name: Blair Conrad
description: One and one and one is three
url: "http://blairconrad.com"

# Author info
author_name: Blair Conrad
author_image_path: /images/author-image.png
author_bio: |
    Software developer at Agfa HealthCare
    More <a href=/about/>about me</a>.

# External services
github_url: "https://github.com/blairconrad"
twitter_url: "https://twitter.com/Hippopottoman"
linkedin_url: "https://linkedin.com/in/blairconrad"
feed_url: "http://feeds.feedburner.com/BlairConrad"
email: "blair@blairconrad.com"
disqus_short_name: blairconrad

# For Google Authorship https://plus.google.com/authorship
googleplus_profile: "BlairConrad"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
relative_permalinks: false
pygments: true
excerpt_separator: <!--more--> 
image_dir: http://blairconrad.com/images