name: Publish

on:
  schedule:
    - cron: '47 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: build site
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        inv preview
    - name: publish changes
      run: |
        git config --local user.email "blair@blairconrad.com"
        git config --local user.name "Blair Conrad [bot]"
        git add .
        git diff --name-only --exit-code || { git commit -m "Publish article on $(date --iso-8601=date)"; git push; }
