name: Publish

on:
  schedule:
    - cron: '17 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: publish
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        inv publish --token ${{ secrets.GITHUB_TOKEN }}